#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_TYPE        1
#define AUDIO_I2S_MIC_GPIO_WS     GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK    GPIO_NUM_6
#define AUDIO_I2S_MIC_GPIO_DIN    GPIO_NUM_5

#define AUDIO_I2S_SPK_TYPE        3
#define AUDIO_I2S_SPK_GPIO_DOUT   GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK   GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK   GPIO_NUM_16
#define AUDIO_I2S_SPK_GPIO_SD     GPIO_NUM_NC
#define AUDIO_I2S_SPK_GPIO_MCLK   GPIO_NUM_NC
#define AUDIO_I2S_SPK_GPIO_SDA    GPIO_NUM_NC
#define AUDIO_I2S_SPK_GPIO_SCL    GPIO_NUM_NC
#define AUDIO_I2S_SPK_I2C_ADDR    0

#else

#define AUDIO_I2S_GPIO_WS     GPIO_NUM_NC
#define AUDIO_I2S_GPIO_BCLK   GPIO_NUM_NC
#define AUDIO_I2S_GPIO_DIN    GPIO_NUM_NC
#define AUDIO_I2S_GPIO_DOUT   GPIO_NUM_NC
#define AUDIO_I2S_GPIO_MCLK   GPIO_NUM_NC

#endif

#define AUDIO_CODEC_TYPE        0
#define AUDIO_CODEC_PA_CTRL     GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA     GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SCL     GPIO_NUM_NC
#define AUDIO_CODEC_I2C_ADDR    48

#define AUDIO_MIC_CHANNEL       0
#define AUDIO_SPK_CHANNEL       0
#define AUDIO_MIC_GAIN          2
#define AUDIO_SPK_GAIN          3

#define DISPLAY_DIRVER_TYPE     1
#define DISPLAY_WIDTH           240
#define DISPLAY_HEIGHT          296
#define DISPLAY_ROTATE          0
#define DISPLAY_RGB_ORDER       1
#define DISPLAY_INVERT_COLOR    1
#define DISPLAY_BACKLIGHT_INVERT 0
#define DISPLAY_SPI_MODE        0
#define DISPLAY_OFFSET_X        0
#define DISPLAY_OFFSET_Y        6
#define DISPLAY_MIRROR_X        false
#define DISPLAY_MIRROR_Y        false
#define DISPLAY_SWAP_XY         false

#define DISPLAY_BACKLIGHT_PIN   GPIO_NUM_42
#define DISPLAY_MOSI_PIN        GPIO_NUM_47
#define DISPLAY_DC_PIN          GPIO_NUM_40
#define DISPLAY_CLK_PIN         GPIO_NUM_21
#define DISPLAY_RST_PIN         GPIO_NUM_45
#define DISPLAY_CS_PIN          GPIO_NUM_41

#define DISPLAY_TOUCH_TYPE      0
#define DISPLAY_TP_SDA_PIN      GPIO_NUM_NC
#define DISPLAY_TP_SCL_PIN      GPIO_NUM_NC
#define DISPLAY_TP_INT_PIN      GPIO_NUM_NC
#define DISPLAY_TP_RST_PIN      GPIO_NUM_NC

#define BOOT_BUTTON_GPIO        GPIO_NUM_9
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_0
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_3
#define PLAY_PREV_BUTTON_GPIO   GPIO_NUM_NC
#define PLAY_NEXT_BUTTON_GPIO   GPIO_NUM_NC
#define PAUSE_RESUME_BUTTON_GPIO GPIO_NUM_NC
#define TALK_BUTTON_GPIO        GPIO_NUM_NC
#define MUTE_BUTTON_GPIO        GPIO_NUM_NC
#define RESTART_BUTTON_GPIO     GPIO_NUM_NC
#define TOUCH_BUTTON_GPIO       GPIO_NUM_8

#define SDMMC_GPIO_MODE         1
#define SDMMC_SCK_GPIO          GPIO_NUM_14
#define SDMMC_CMD_GPIO          GPIO_NUM_39
#define SDMMC_D0_GPIO           GPIO_NUM_38
#define SDMMC_D3_GPIO           GPIO_NUM_NC

#define BATTERY_MANAGER         1
#define BATTERY_ADC_GPIO        GPIO_NUM_1
#define BATTERY_CHG_GPIO        GPIO_NUM_2
#define BATTERY_CHG_LEVEL       1
#define BATTERY_UPPER_RES       10
#define BATTERY_LOWER_RES       10
#define BATTERY_VBAT_FULL       4200
#define BATTERY_VBAT_LOW        3400

#define SCREEN_SLEEP_TIMER      0
#define POWER_SLEEP_TIMER       0
#define POWER_CTRL_GPIO         GPIO_NUM_NC
#define POWER_CTRL_MODE         0
#define SLEEP_WAKEUP_GPIO       GPIO_NUM_NC

#define BOOT_BUTTON_LEVEL       0
#define POWER_OFF_BY_BOOT       0
#define SLEEP_WAKEUP_BY_BOOT    1
#define SLEEP_WAKEUP_BY_VOLUME  1
#define CONFIG_MODE_BY_BOOT     1

#define HIGH_LEVEL_GPIO         GPIO_NUM_NC
#define LOW_LEVEL_GPIO          GPIO_NUM_NC

#define CAPSULE_OFFSET_Y        -12
#define CAPSULE_MAX_WIDTH       90

#define LCD_SHAPE_STYLE         1
#define LCD_PCLK_MHZ            40

#define DISPLAY_SDA_PIN         GPIO_NUM_47
#define DISPLAY_SCL_PIN         GPIO_NUM_21
#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define LAMP_GPIO               GPIO_NUM_NC

#endif // _BOARD_CONFIG_H_