#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/spi_master.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// ES8311 pins, verified against Netlist_PCB_Main_2026-08-13.net.
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_13
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_14
#define AUDIO_I2S_GPIO_MCLK     GPIO_NUM_21
#define AUDIO_I2S_GPIO_BCLK     GPIO_NUM_18
#define AUDIO_I2S_GPIO_WS       GPIO_NUM_17
#define AUDIO_I2S_GPIO_DOUT     GPIO_NUM_16
#define AUDIO_I2S_GPIO_DIN      GPIO_NUM_15
#define AUDIO_CODEC_PA_PIN      GPIO_NUM_40
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO GPIO_NUM_0

// SSD2683ZA 4.2-inch 400x300 2-bpp panel.
#define EPD_SPI_NUM   SPI3_HOST
#define EPD_MOSI_PIN  GPIO_NUM_6
#define EPD_SCK_PIN   GPIO_NUM_8
#define EPD_CS_PIN    GPIO_NUM_9
#define EPD_DC_PIN    GPIO_NUM_10
#define EPD_RST_PIN   GPIO_NUM_11
#define EPD_BUSY_PIN  GPIO_NUM_12
#define EPD_BUSY_LEVEL 0

#define DISPLAY_WIDTH  400
#define DISPLAY_HEIGHT 300

#endif
